name: Run Tests via Pytest

on:
  pull_request_target:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout code (PR)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout code (Push)
        if: github.event_name == 'push'
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pipx install poetry==2.1.2

      - name: Install dependencies
        run: |
          poetry install --sync -E all

      - name: Test with pytest
        run: |
          poetry run coverage run -m pytest  -v -s

      - name: Generate Coverage Report
        run: |
          poetry run coverage report -m